version: '3.8'

services:
  wordpress:
    image: <placeholder-image>
    restart: always
    read_only: true
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME:
      WORDPRESS_CONFIG_EXTRA:
    volumes:
      - type: bind
        source: /data/wp-content
        target: /var/www/html/wp-content
      - type: tmpfs
        target: /run/lock/apache2
      - type: tmpfs
        target: /run/apache2
      - type: tmpfs
        target: /var/cache/mod_pagespeed
      - type: tmpfs
        target: /var/log/pagespeed
      - type: tmpfs
        target: /tmp

