---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS WordPress S3'

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'General configuration'
        Parameters:
          - 'BaseName'
          - 'Environment'
      - Label:
          default: 'SSM configuration'
        Parameters:
          - 'SsmKeyPrefix'
    ParameterLabels:
      BaseName:
        default: 'Base resource name'
      Environment:
        default: 'Environment'
      SsmKeyPrefix:
        default: 'Key prefix'

Parameters:

  BaseName:
    Description: 'This name will be used to build identifiers for the components in the stack'
    Type: 'String'
    AllowedPattern: '[-_a-z0-9]+'
    ConstraintDescription: 'Invalid name. Only lowercase letters, numbers, underscores and hyphens are allowed.'
    Default: 's3'

  Environment:
    Description: 'Stack environment name'
    Type: 'String'
    AllowedValues:
      - 'Pro'
      - 'Pre'
    Default: 'Pro'

  SsmKeyPrefix:
    Description: 'Key prefix for AWS Systems Manager Parameters created in this stack'
    Type: 'String'
    Default: '/s3'

Resources:

  ContentBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${BaseName}-content'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: 'Name'
          Value: !Sub '${BaseName}-content'
        - Key: 'Env'
          Value: !Ref 'Environment'

  BackupBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'
    UpdateReplacePolicy: 'Retain'
    Properties:
      BucketName: !Sub '${BaseName}-backup'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: 'Name'
          Value: !Sub '${BaseName}-backup'
        - Key: 'Env'
          Value: !Ref 'Environment'

  SsmContentBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${SsmKeyPrefix}/content-bucket-name'
      Type: String
      Value: !Ref 'ContentBucket'
      Description: !Sub '${AWS::StackName} - Content Bucket Name'
      Tags:
        Name: !Sub '${BaseName}-contentbucketname'
        Env: !Ref 'Environment'

  SsmContentBucketArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${SsmKeyPrefix}/content-bucket-arn'
      Type: String
      Value: !GetAtt 'ContentBucket.Arn'
      Description: !Sub '${AWS::StackName} - Content Bucket ARN'
      Tags:
        Name: !Sub '${BaseName}-contentbucketarn'
        Env: !Ref 'Environment'

  SsmContentBucketDomain:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${SsmKeyPrefix}/content-bucket-dns'
      Type: String
      Value: !GetAtt 'ContentBucket.DomainName'
      Description: !Sub '${AWS::StackName} - Content Bucket Domain Name'
      Tags:
        Name: !Sub '${BaseName}-contentbucketdns'
        Env: !Ref 'Environment'

  SsmBackupBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${SsmKeyPrefix}/backup-bucket-name'
      Type: String
      Value: !Ref 'BackupBucket'
      Description: !Sub '${AWS::StackName} - Backup Bucket Name'
      Tags:
        Name: !Sub '${BaseName}-backupbucketname'
        Env: !Ref 'Environment'

  SsmBackupBucketArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${SsmKeyPrefix}/backup-bucket-arn'
      Type: String
      Value: !GetAtt 'BackupBucket.Arn'
      Description: !Sub '${AWS::StackName} - Backup Bucket ARN'
      Tags:
        Name: !Sub '${BaseName}-backupbucketarn'
        Env: !Ref 'Environment'

  SsmBackupBucketDomain:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${SsmKeyPrefix}/backup-bucket-dns'
      Type: String
      Value: !GetAtt 'BackupBucket.DomainName'
      Description: !Sub '${AWS::StackName} - Backup Bucket Domain Name'
      Tags:
        Name: !Sub '${BaseName}-backupbucketdns'
        Env: !Ref 'Environment'

Outputs:

  ContentBucketName:
    Description: 'Content bucket name'
    Value: !Ref 'ContentBucket'
    Export:
      Name: !Sub '${AWS::StackName}-ContentBucketName'

  ContentBucketArn:
    Description: 'Content bucket ARN'
    Value: !GetAtt 'ContentBucket.Arn'
    Export:
      Name: !Sub '${AWS::StackName}-ContentBucketArn'

  ContentBucketDomain:
    Description: 'Content bucket domain name'
    Value: !GetAtt 'ContentBucket.DomainName'
    Export:
      Name: !Sub '${AWS::StackName}-ContentBucketDomain'

  BackupBucketName:
    Description: 'Backup bucket name'
    Value: !Ref 'BackupBucket'
    Export:
      Name: !Sub '${AWS::StackName}-BackupBucketName'

  BackupBucketArn:
    Description: 'Backup bucket ARN'
    Value: !GetAtt 'BackupBucket.Arn'
    Export:
      Name: !Sub '${AWS::StackName}-BackupBucketArn'

  BackupBucketDomain:
    Description: 'Backup bucket domain name'
    Value: !GetAtt 'BackupBucket.DomainName'
    Export:
      Name: !Sub '${AWS::StackName}-BackupBucketDomain'
