---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS WordPress CloudFront'

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'General configuration'
        Parameters:
          - 'BaseName'
          - 'Environment'
      - Label:
          default: 'CloudFront configuration'
        Parameters:
          - 'WordPressBalancer'
          - 'WordPressBucketDns'
          - 'WordPressBucketArn'
          - 'WordPressBucketName'
          - 'WordPressDnsNames'
          - 'Certificate'
    ParameterLabels:
      BaseName:
        default: 'Base resource name'
      Environment:
        default: 'Environment'
      WordPressBalancer:
        default: 'WordPress service load balancer endpoint'
      WordPressBucketDns:
        default: 'WordPress content S3 bucket domain name'
      WordPressBucketArn:
        default: 'WordPress content S3 bucket ARN'
      WordPressBucketName:
        default: 'WordPress content S3 bucket name'
      WordPressDnsNames:
        default: 'WordPress DNS domain names'
      Certificate:
        default: 'TLS Certificate'

Parameters:

  BaseName:
    Description: 'This name will be used to build identifiers for the components in the stack'
    Type: 'String'
    AllowedPattern: '[-_a-z0-9]+'
    ConstraintDescription: 'Invalid name. Only lowercase letters, numbers, underscores and hyphens are allowed.'
    Default: 'cdn'

  Environment:
    Description: 'Stack environment name'
    Type: 'String'
    AllowedValues:
      - 'Pro'
      - 'Pre'
    Default: 'Pro'

  WordPressBalancer:
    Description: 'AWS SSM Parameter name storing load balancer DNS endpoint'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/loadbalancer'

  WordPressBucketDns:
    Description: 'AWS SSM Parameter name storing S3 bucket domain name'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/s3bucket-dns'

  WordPressBucketArn:
    Description: 'AWS SSM Parameter name storing S3 bucket ARN'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/s3bucket-arn'

  WordPressBucketName:
    Description: 'AWS SSM Parameter name storing S3 bucket name'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/s3bucket-name'

  WordPressDnsNames:
    Description: 'Domain names to be used by WordPress'
    Type: 'AWS::SSM::Parameter::Value<List<String>>'
    Default: '/wordpress/domain-names'

  Certificate:
    Description: 'AWS SSM Parameter name storing the TLS certificate ARN (certificate must be stored in ACM in the us-east-1 region)'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/cdn/certificate'

Resources:

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: 'WordPress service'
        Aliases: !Ref 'WordPressDnsNames'
        ViewerCertificate:
          AcmCertificateArn: !Ref 'Certificate'
          MinimumProtocolVersion: 'TLSv1'
          SslSupportMethod: 'sni-only'
        Origins:
          - Id: !Sub '${BaseName}-S3'
            DomainName: !Ref 'WordPressBucketDns'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${ContentIdentity}'
          - Id: !Sub '${BaseName}-ELB'
            DomainName: !Ref 'WordPressBalancer'
            CustomOriginConfig:
              OriginProtocolPolicy: 'match-viewer'
        DefaultCacheBehavior:
          TargetOriginId: !Sub '${BaseName}-ELB'
          ViewerProtocolPolicy: 'redirect-to-https'
          CachePolicyId: !Ref 'DefaultCachePolicy'
          Compress: true
          AllowedMethods:
            - 'GET'
            - 'HEAD'
            - 'OPTIONS'
            - 'PUT'
            - 'PATCH'
            - 'POST'
            - 'DELETE'
          CachedMethods:
            - 'GET'
            - 'HEAD'
            - 'OPTIONS'
        CacheBehaviors:
          - PathPattern: '/wp-content/*'
            TargetOriginId: !Sub '${BaseName}-S3'
            ViewerProtocolPolicy: 'redirect-to-https'
            CachePolicyId: !Ref 'ContentCachePolicy'
            Compress: true
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
            CachedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
          - PathPattern: '/.well-known/acme-challenge/*'
            TargetOriginId: !Sub '${BaseName}-ELB'
            ViewerProtocolPolicy: 'allow-all'
            CachePolicyId: !Ref 'AcmeChallengeCachePolicy'
            Compress: true
            AllowedMethods:
              - 'GET'
              - 'HEAD'
            CachedMethods:
              - 'GET'
              - 'HEAD'
      Tags:
        - Key: 'Name'
          Value: !Ref 'BaseName'
        - Key: 'Env'
          Value: !Ref 'Environment'

  DefaultCachePolicy:
    Type: 'AWS::CloudFront::CachePolicy'
    Properties:
      CachePolicyConfig:
        Comment: 'WordPress Default Cache Behavior'
        DefaultTTL: 60
        MaxTTL: 31536000
        MinTTL: 0
        Name: !Sub '${BaseName}-default'
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: 'whitelist'
            Cookies:
              - 'comment_author_*'
              - 'comment_author_email_*'
              - 'comment_author_url_*'
              - 'wordpress_logged_in_*'
              - 'wordpress_test_cookie'
              - 'wp-settings-*'
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: 'whitelist'
            Headers:
              - 'Host'
              - 'Origin'
              - 'Access-Control-Request-Headers'
              - 'Access-Control-Request-Method'
          QueryStringsConfig:
            QueryStringBehavior: 'all'

  ContentCachePolicy:
    Type: 'AWS::CloudFront::CachePolicy'
    Properties:
      CachePolicyConfig:
        Comment: 'WordPress Content Cache Behavior'
        DefaultTTL: 3600
        MaxTTL: 31536000
        MinTTL: 0
        Name: !Sub '${BaseName}-content'
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: 'none'
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: 'whitelist'
            Headers:
              - 'Origin'
              - 'Access-Control-Request-Headers'
              - 'Access-Control-Request-Method'
          QueryStringsConfig:
            QueryStringBehavior: 'none'

  AcmeChallengeCachePolicy:
    Type: 'AWS::CloudFront::CachePolicy'
    Properties:
      CachePolicyConfig:
        Comment: 'LetsEncrypt Acme Challenge Cache Behavior'
        DefaultTTL: 0
        MaxTTL: 31536000
        MinTTL: 0
        Name: !Sub '${BaseName}-acme-challenge'
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: 'none'
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: 'whitelist'
            Headers:
              - 'Host'
              - 'Origin'
          QueryStringsConfig:
            QueryStringBehavior: 'none'

  ContentBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref 'WordPressBucketName'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt 'ContentIdentity.S3CanonicalUserId'
            Action:
              - 's3:GetObject'
            Resource: !Sub '${WordPressBucketArn}/*'

  ContentIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'WordPress content CloudFront identity'

Outputs:

  DistributionId:
    Description: 'Distribution identifier'
    Value: !Ref 'Distribution'
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'

  DistributionDnsName:
    Description: 'Distribution domain name'
    Value: !GetAtt 'Distribution.DomainName'
    Export:
      Name: !Sub '${AWS::StackName}-DistributionDnsName'
