---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS WordPress ECS/Fargate'

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'General configuration'
        Parameters:
          - 'BaseName'
          - 'Environment'
          - 'SiteDomain'
      - Label:
          default: 'Network configuration'
        Parameters:
          - 'VpcId'
          - 'Subnets'
      - Label:
          default: 'Load Balancer configuration'
        Parameters:
          - 'ListenerHttpArn'
          - 'ListenerHttpsArn'
          - 'LoadBalancerSG'
      - Label:
          default: 'Container configuration'
        Parameters:
          - 'SetupImage'
          - 'WordPressImage'
          - 'TaskCpu'
          - 'TaskMemory'
          - 'TaskCount'
      - Label:
          default: 'Database configuration'
        Parameters:
          - 'DatabaseHost'
          - 'DatabaseSG'
          - 'DatabaseName'
          - 'DatabaseMasterUser'
          - 'DatabaseMasterPassword'
          - 'DatabaseWpUser'
          - 'DatabaseWpPassword'
      - Label:
          default: 'EFS configuration'
        Parameters:
          - 'FileSystemId'
          - 'FileSystemSG'
    ParameterLabels:
      BaseName:
        default: 'Base resource name'
      Environment:
        default: 'Environment'
      SiteDomain:
        default: 'Site Domain'
      VpcId:
        default: 'VPC Identifier'
      Subnets:
        default: 'VPC Subnets'
      ListenerHttpArn:
        default: 'HTTP listener identifier'
      ListenerHttpsArn:
        default: 'HTTPS listener identifier'
      LoadBalancerSG:
        default: 'Load Balancer security group'
      SetupImage:
        default: 'WordPress setup container image repository URL'
      WordPressImage:
        default: 'WordPress service container image repository URL'
      TaskCpu:
        default: 'Container CPU'
      TaskMemory:
        default: 'Container memory'
      TaskCount:
        default: 'Desired task count'
      DatabaseHost:
        default: 'Database host'
      DatabaseSG:
        default: 'Database security group'
      DatabaseName:
        default: 'Database name'
      DatabaseMasterUser:
        default: 'Database master user'
      DatabaseMasterPassword:
        default: 'Database master password'
      DatabaseWpUser:
        default: 'Database WordPress user'
      DatabaseWpPassword:
        default: 'Database WordPress password'
      FileSystemId:
        default: 'FileSystem identifier'
      FileSystemSG:
        default: 'FileSystem security group'

Parameters:

  BaseName:
    Description: 'This name will be used to build identifiers for the components in the stack'
    Type: 'String'
    AllowedPattern: '[-_a-z0-9]+'
    ConstraintDescription: 'Invalid name. Only lowercase letters, numbers, underscores and hyphens are allowed.'
    Default: 'ecs'

  Environment:
    Description: 'Stack environment name'
    Type: 'String'
    AllowedValues:
      - 'Pro'
      - 'Pre'
    Default: 'Pro'

  SiteDomain:
    Description: 'WordPress Site Domain'
    Type: 'String'
    Default: 'blog.wordpress.local'

  VpcId:
    Description: 'AWS SSM Parameter name storing the VPC identifier'
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>'
    Default: '/network/vpc-id'

  Subnets:
    Description: 'AWS SSM Parameter name storing subnets for ECS containers'
    Type: 'AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>'
    Default: '/network/subnets'

  ListenerHttpArn:
    Description: 'AWS SSM Parameter name containing the load balancer HTTP listener ARN'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/balancer/listenerhttp-arn'

  ListenerHttpsArn:
    Description: 'AWS SSM Parameter name containing the load balancer HTTPS listener ARN'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/balancer/listenerhttps-arn'

  LoadBalancerSG:
    Description: 'AWS SSM Parameter name containing the load balancer security group identifier'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/balancer/security-group'

  SetupImage:
    Description: 'AWS SSM Parameter name containing the WordPress setup Docker image repository'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/repository/wordpress-setup'

  WordPressImage:
    Description: 'AWS SSM Parameter name containing the WordPress service Docker image repository'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/repository/wordpress-service'

  TaskCpu:
    Description: 'CPU assigned to the container. 1024 is 1 CPU.'
    Type: 'Number'
    Default: 256

  TaskMemory:
    Description: 'Memory assigned to the container (in megabytes)'
    Type: 'Number'
    Default: 512

  TaskCount:
    Description: 'Copies of the service to run'
    Type: 'Number'
    Default: 1

  DatabaseHost:
    Description: 'AWS SSM Parameter name containing the database writer endpoint for the WordPress service'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/writer-endpoint'

  DatabaseSG:
    Description: 'AWS SSM Parameter name containing the database security group identifier'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/security-group'

  DatabaseName:
    Description: 'AWS SSM Parameter name containing the WordPress service database name'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/name'

  DatabaseMasterUser:
    Description: 'AWS SSM Parameter name containing the database username for the RDS administrative account'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/masteruser'

  DatabaseMasterPassword:
    Description: 'AWS SSM Parameter name containing the database password for the RDS administrative account. This key is used to inject secrets inside the WordPress service container.'
    Type: 'AWS::SSM::Parameter::Name'
    Default: '/database/masterpassword'

  DatabaseWpUser:
    Description: 'AWS SSM Parameter name containing the database username for the WordPress service'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/wpuser'

  DatabaseWpPassword:
    Description: 'AWS SSM Parameter name containing the database password for the WordPress service. This key is used to inject secrets inside the WordPress service container.'
    Type: 'AWS::SSM::Parameter::Name'
    Default: '/database/wppassword'

  FileSystemId:
    Description: 'AWS SSM Parameter name containing the EFS filesystem identifier'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/filesystem/filesystem-id'

  FileSystemSG:
    Description: 'AWS SSM Parameter name containing the EFS filesystem security group identifier'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/filesystem/security-group'

Conditions:
  HasHttpsListener: !Not [ !Equals [ !Ref 'ListenerHttpArn', !Ref 'ListenerHttpsArn' ] ]

Resources:

  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Ref 'BaseName'
      RequiresCompatibilities:
        - 'FARGATE'
      NetworkMode: 'awsvpc'
      Cpu: !Ref 'TaskCpu'
      Memory: !Ref 'TaskMemory'
      ExecutionRoleArn: !GetAtt 'TaskExecutionRole.Arn'
      ContainerDefinitions:
        - Name: 'wordpress-setup'
          Essential: false
          Image: !Ref 'SetupImage'
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Ref 'CloudWatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: 'wordpress-setup'
          Environment:
            - Name: 'DB_HOST'
              Value: !Ref 'DatabaseHost'
            - Name: 'DB_USER'
              Value: !Ref 'DatabaseMasterUser'
            - Name: 'WP_DATABASE'
              Value: !Ref 'DatabaseName'
            - Name: 'WP_USER'
              Value: !Ref 'DatabaseWpUser'
          Secrets:
            - Name: 'DB_PASSWORD'
              ValueFrom: !Ref 'DatabaseMasterPassword'
            - Name: 'WP_PASSWORD'
              ValueFrom: !Ref 'DatabaseWpPassword'
        - Name: 'wordpress-service'
          Essential: true
          Image: !Ref 'WordPressImage'
          DependsOn:
            - Condition: 'SUCCESS'
              ContainerName: 'wordpress-setup'
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Ref 'CloudWatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: 'wordpress-service'
          MountPoints:
            - ContainerPath: '/var/www/html/wp-content'
              SourceVolume: 'content'
          Environment:
            - Name: 'WORDPRESS_DB_HOST'
              Value: !Ref 'DatabaseHost'
            - Name: 'WORDPRESS_DB_NAME'
              Value: !Ref 'DatabaseName'
            - Name: 'WORDPRESS_DB_USER'
              Value: !Ref 'DatabaseWpUser'
            - Name: 'WORDPRESS_CONFIG_EXTRA'
              Value: !Sub
                - |
                  define('WP_HOME', '${Scheme}://${SiteDomain}');
                  define('WP_SITEURL', '${Scheme}://${SiteDomain}');
                  define('FS_METHOD', 'direct');
                - Scheme: !If [ 'HasHttpsListener', 'https', 'http' ]
          Secrets:
            - Name: 'WORDPRESS_DB_PASSWORD'
              ValueFrom: !Ref 'DatabaseWpPassword'
          PortMappings:
            - ContainerPort: 80
      Volumes:
        - Name: 'content'
          EFSVolumeConfiguration:
            FilesystemId: !Ref 'FileSystemId'
            AuthorizationConfig:
              AccessPointId: !Ref 'ContentAccessPoint'
            TransitEncryption: 'ENABLED'

  TaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'SSMParametersPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'ssm:GetParameter*'
                Resource: '*'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      Tags:
        - Key: 'Name'
          Value: !Ref 'BaseName'
        - Key: 'Env'
          Value: !Ref 'Environment'

  TaskService:
    Type: 'AWS::ECS::Service'
    DependsOn:
      - 'ListenerHttpRule'
    Properties:
      ServiceName: !Ref 'BaseName'
      Cluster: !Ref 'ContainerCluster'
      LaunchType: 'FARGATE'
      PlatformVersion: '1.4.0'
      DesiredCount: !Ref 'TaskCount'
      TaskDefinition: !Ref 'TaskDefinition'
      HealthCheckGracePeriodSeconds: 90
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          SecurityGroups:
            - !Ref 'ServiceSG'
          Subnets: !Ref 'Subnets'
      LoadBalancers:
        - ContainerName: 'wordpress-service'
          ContainerPort: 80
          TargetGroupArn: !Ref 'TargetGroup'
      PropagateTags: 'SERVICE'
      Tags:
        - Key: 'Name'
          Value: !Ref 'BaseName'
        - Key: 'Env'
          Value: !Ref 'Environment'

  ContainerCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref 'BaseName'
      Tags:
        - Key: 'Name'
          Value: !Ref 'BaseName'
        - Key: 'Env'
          Value: !Ref 'Environment'

  CloudWatchLogsGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Ref 'BaseName'
      RetentionInDays: 365

  ServiceSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable access to service'
      VpcId: !Ref 'VpcId'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref 'LoadBalancerSG'
      Tags:
        - Key: 'Name'
          Value: !Sub '${BaseName}-service'
        - Key: 'Env'
          Value: !Ref 'Environment'

  FileSystemIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref 'FileSystemSG'
      IpProtocol: tcp
      FromPort: 2049
      ToPort: 2049
      SourceSecurityGroupId: !Ref 'ServiceSG'

  DatabaseIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref 'DatabaseSG'
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref 'ServiceSG'

  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: !Sub '${BaseName}-service'
      Port: 80
      Protocol: 'HTTP'
      VpcId: !Ref 'VpcId'
      TargetType: 'ip'
      HealthCheckPath: '/'
      HealthCheckProtocol: 'HTTP'
      HealthCheckPort: 'traffic-port'
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-399
      Tags:
        - Key: 'Name'
          Value: !Sub '${BaseName}-service'
        - Key: 'Env'
          Value: !Ref 'Environment'

  ListenerHttpRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      ListenerArn: !Ref 'ListenerHttpArn'
      Priority: 10
      Conditions:
        - Field: 'host-header'
          Values:
            - !Ref 'SiteDomain'
      Actions:
        - Type: 'forward'
          TargetGroupArn: !Ref 'TargetGroup'

  ListenerHttpsRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Condition: HasHttpsListener
    Properties:
      ListenerArn: !Ref 'ListenerHttpsArn'
      Priority: 10
      Conditions:
        - Field: 'host-header'
          Values:
            - !Ref 'SiteDomain'
      Actions:
        - Type: 'forward'
          TargetGroupArn: !Ref 'TargetGroup'

  ContentAccessPoint:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      FileSystemId: !Ref 'FileSystemId'
      RootDirectory:
        Path: '/wp-content'
        CreationInfo:
          OwnerUid: '33'
          OwnerGid: '33'
          Permissions: '0755'
      AccessPointTags:
        - Key: 'Name'
          Value: !Sub '${BaseName}-content'
        - Key: 'Env'
          Value: !Ref 'Environment'

Outputs:

  ServiceSG:
    Description: 'Service security group'
    Value: !Ref 'ServiceSG'
    Export:
      Name: !Sub '${AWS::StackName}-ServiceSG'
