---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS WordPress ECS/EC2'

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'General configuration'
        Parameters:
          - 'BaseName'
          - 'Environment'
      - Label:
          default: 'Network configuration'
        Parameters:
          - 'VpcId'
          - 'Subnets'
      - Label:
          default: 'Load Balancer configuration'
        Parameters:
          - 'LoadBalancerEndpoint'
          - 'LoadBalancerHostedZoneId'
          - 'LoadBalancerSG'
          - 'ListenerHttpArn'
          - 'ListenerHttpsArn'
          - 'WordPressDnsName'
          - 'WordPressHostedZone'
      - Label:
          default: 'AutoScaling configuration'
        Parameters:
          - 'ImageId'
          - 'InstanceType'
          - 'InstanceCount'
      - Label:
          default: 'Container configuration'
        Parameters:
          - 'SetupImage'
          - 'WordPressImage'
          - 'TaskCpu'
          - 'TaskMemory'
          - 'TaskCount'
      - Label:
          default: 'Database configuration'
        Parameters:
          - 'DatabaseHost'
          - 'DatabaseSG'
          - 'DatabaseName'
          - 'DatabaseMasterUser'
          - 'DatabaseMasterPassword'
          - 'DatabaseWpUser'
          - 'DatabaseWpPassword'
      - Label:
          default: 'Storage configuration'
        Parameters:
          - 'ContentBucket'
          - 'BackupBucket'
    ParameterLabels:
      BaseName:
        default: 'Base resource name'
      Environment:
        default: 'Environment'
      VpcId:
        default: 'VPC Identifier'
      Subnets:
        default: 'VPC Subnets'
      LoadBalancerEndpoint:
        default: 'Public DNS endpoint'
      LoadBalancerHostedZoneId:
        default: 'Route53 HostedZone identifier'
      LoadBalancerSG:
        default: 'Security group'
      ListenerHttpArn:
        default: 'HTTP listener identifier'
      ListenerHttpsArn:
        default: 'HTTPS listener identifier'
      WordPressDnsName:
        default: 'WordPress DNS domain name'
      WordPressHostedZone:
        default: 'WordPress Route53 hosted zone name'
      ImageId:
        default: 'Amazon Machine Image'
      InstanceType:
        default: 'Instance type'
      InstanceCount:
        default: 'Desired number of EC2 instances'
      SetupImage:
        default: 'WordPress setup container image repository URL'
      WordPressImage:
        default: 'WordPress service container image repository URL'
      TaskCpu:
        default: 'Container CPU'
      TaskMemory:
        default: 'Container memory'
      TaskCount:
        default: 'Desired task count'
      DatabaseHost:
        default: 'Database host'
      DatabaseSG:
        default: 'Database security group'
      DatabaseName:
        default: 'Database name'
      DatabaseMasterUser:
        default: 'Database master user'
      DatabaseMasterPassword:
        default: 'Database master password'
      DatabaseWpUser:
        default: 'Database WordPress user'
      DatabaseWpPassword:
        default: 'Database WordPress password'
      ContentBucket:
        default: 'WordPress content S3 bucket'
      BackupBucket:
        default: 'WordPress backup S3 bucket'

Parameters:

  BaseName:
    Description: 'This name will be used to build identifiers for the components in the stack'
    Type: 'String'
    AllowedPattern: '[-_a-z0-9]+'
    ConstraintDescription: 'Invalid name. Only lowercase letters, numbers, underscores and hyphens are allowed.'
    Default: 'ecs'

  Environment:
    Description: 'Stack environment name'
    Type: 'String'
    AllowedValues:
      - 'Pro'
      - 'Pre'
    Default: 'Pro'

  VpcId:
    Description: 'AWS SSM Parameter name storing the VPC identifier'
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>'
    Default: '/network/vpc-id'

  Subnets:
    Description: 'AWS SSM Parameter name storing subnets for ECS containers'
    Type: 'AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>'
    Default: '/network/subnets'

  LoadBalancerEndpoint:
    Description: 'AWS SSM Parameter name containing the load balancer DNS endpoint'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/balancer/dns-endpoint'

  LoadBalancerHostedZoneId:
    Description: 'AWS SSM Parameter name containing the load balancer Route53 hosted zone identifier'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/balancer/hostedzone-id'

  LoadBalancerSG:
    Description: 'AWS SSM Parameter name containing the load balancer security group identifier'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/balancer/security-group'

  ListenerHttpArn:
    Description: 'AWS SSM Parameter name containing the load balancer HTTP listener ARN'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/balancer/listenerhttp-arn'

  ListenerHttpsArn:
    Description: 'AWS SSM Parameter name containing the load balancer HTTPS listener ARN'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/balancer/listenerhttps-arn'

  WordPressDnsName:
    Description: 'Domain name to be used by WordPress'
    Type: 'String'
    Default: 'blog.wordpress.local'

  WordPressHostedZone:
    Description: 'Route53 domain name (below which WordPress domain will be registered)'
    Type: 'String'
    Default: ''

  ImageId:
    Description: 'Amazon Machine Image enabled for ECS'
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/ec2/image-id'

  InstanceType:
    Description: 'EC2 instance type'
    Type: 'String'
    Default: 't3.small'

  InstanceCount:
    Description: 'Number of EC2 instances to launch'
    Type: 'Number'
    Default: 1

  SetupImage:
    Description: 'AWS SSM Parameter name containing the WordPress setup Docker image repository'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/repository/wordpress-setup'

  WordPressImage:
    Description: 'AWS SSM Parameter name containing the WordPress service Docker image repository'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/repository/wordpress-service'

  TaskCpu:
    Description: 'CPU assigned to the container. 1024 is 1 CPU.'
    Type: 'Number'
    Default: 256

  TaskMemory:
    Description: 'Memory assigned to the container (in megabytes)'
    Type: 'Number'
    Default: 512

  TaskCount:
    Description: 'Copies of the service to run'
    Type: 'Number'
    Default: 1

  DatabaseHost:
    Description: 'AWS SSM Parameter name containing the database writer endpoint for the WordPress service'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/writer-endpoint'

  DatabaseSG:
    Description: 'AWS SSM Parameter name containing the database security group identifier'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/security-group'

  DatabaseName:
    Description: 'AWS SSM Parameter name containing the WordPress service database name'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/name'

  DatabaseMasterUser:
    Description: 'AWS SSM Parameter name containing the database username for the RDS administrative account'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/masteruser'

  DatabaseMasterPassword:
    Description: 'AWS SSM Parameter name containing the database password for the RDS administrative account. This key is used to inject secrets inside the WordPress service container.'
    Type: 'AWS::SSM::Parameter::Name'
    Default: '/database/masterpassword'

  DatabaseWpUser:
    Description: 'AWS SSM Parameter name containing the database username for the WordPress service'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/database/wpuser'

  DatabaseWpPassword:
    Description: 'AWS SSM Parameter name containing the database password for the WordPress service. This key is used to inject secrets inside the WordPress service container.'
    Type: 'AWS::SSM::Parameter::Name'
    Default: '/database/wppassword'

  ContentBucket:
    Description: 'AWS SSM Parameter name storing WordPress content S3 bucket'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/bucket/content'

  BackupBucket:
    Description: 'AWS SSM Parameter name storing WordPress backup S3 bucket'
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/bucket/backup'

Conditions:
  HasHttpsListener: !Not [ !Equals [ !Ref 'ListenerHttpArn', !Ref 'ListenerHttpsArn' ] ]
  HasHostedZone: !Not [ !Equals [ !Ref 'WordPressHostedZone', '' ] ]

Resources:

  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Ref 'BaseName'
      RequiresCompatibilities:
        - 'EC2'
      NetworkMode: 'bridge'
      Cpu: !Ref 'TaskCpu'
      Memory: !Ref 'TaskMemory'
      ExecutionRoleArn: !GetAtt 'TaskExecutionRole.Arn'
      ContainerDefinitions:
        - Name: 'wordpress-setup'
          Essential: false
          Image: !Ref 'SetupImage'
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Ref 'CloudWatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: 'wordpress-setup'
          Environment:
            - Name: 'DB_HOST'
              Value: !Ref 'DatabaseHost'
            - Name: 'DB_USER'
              Value: !Ref 'DatabaseMasterUser'
            - Name: 'WP_DATABASE'
              Value: !Ref 'DatabaseName'
            - Name: 'WP_USER'
              Value: !Ref 'DatabaseWpUser'
          Secrets:
            - Name: 'DB_PASSWORD'
              ValueFrom: !Ref 'DatabaseMasterPassword'
            - Name: 'WP_PASSWORD'
              ValueFrom: !Ref 'DatabaseWpPassword'
        - Name: 'wordpress-service'
          Essential: true
          Image: !Ref 'WordPressImage'
          DependsOn:
            - Condition: 'SUCCESS'
              ContainerName: 'wordpress-setup'
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Ref 'CloudWatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: 'wordpress-service'
          MountPoints:
            - ContainerPath: '/var/www/html/wp-content'
              SourceVolume: 'content'
          Environment:
            - Name: 'WORDPRESS_DB_HOST'
              Value: !Ref 'DatabaseHost'
            - Name: 'WORDPRESS_DB_NAME'
              Value: !Ref 'DatabaseName'
            - Name: 'WORDPRESS_DB_USER'
              Value: !Ref 'DatabaseWpUser'
            - Name: 'WORDPRESS_CONFIG_EXTRA'
              Value: !Sub
                - |
                  define('WP_HOME', '${Scheme}://${WordPressDnsName}');
                  define('WP_SITEURL', '${Scheme}://${WordPressDnsName}');
                  define('FS_METHOD', 'direct');
                - Scheme: !If [ 'HasHttpsListener', 'https', 'http' ]
          Secrets:
            - Name: 'WORDPRESS_DB_PASSWORD'
              ValueFrom: !Ref 'DatabaseWpPassword'
          PortMappings:
            - ContainerPort: 80
      Volumes:
        - Name: 'content'
          Host:
            SourcePath: '/data/wp-content'

  TaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'SSMParametersPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'ssm:GetParameter*'
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${DatabaseMasterPassword}'
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${DatabaseWpPassword}'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      Tags:
        - Key: 'Name'
          Value: !Ref 'BaseName'
        - Key: 'Env'
          Value: !Ref 'Environment'

  TaskService:
    Type: 'AWS::ECS::Service'
    DependsOn:
      - 'AutoScalingGroup'
      - 'ListenerHttpRule'
    Properties:
      ServiceName: !Ref 'BaseName'
      Cluster: !Ref 'ContainerCluster'
      LaunchType: 'EC2'
      DesiredCount: !Ref 'TaskCount'
      TaskDefinition: !Ref 'TaskDefinition'
      HealthCheckGracePeriodSeconds: 90
      LoadBalancers:
        - ContainerName: 'wordpress-service'
          ContainerPort: 80
          TargetGroupArn: !Ref 'TargetGroup'
      PropagateTags: 'SERVICE'
      Tags:
        - Key: 'Name'
          Value: !Ref 'BaseName'
        - Key: 'Env'
          Value: !Ref 'Environment'

  ContainerCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref 'BaseName'
      Tags:
        - Key: 'Name'
          Value: !Ref 'BaseName'
        - Key: 'Env'
          Value: !Ref 'Environment'

  CloudWatchLogsGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Ref 'BaseName'
      RetentionInDays: 365

  LaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref 'InstanceProfile'
      ImageId: !Ref 'ImageId'
      InstanceType: !Ref 'InstanceType'
      SecurityGroups:
        - !Ref 'InstanceSG'
      BlockDeviceMappings:
        - DeviceName: '/dev/sda1'
          Ebs:
            VolumeSize: 30
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # Register instance with ECS cluster
          cat <<'EOF' >> /etc/ecs/ecs.config
          ECS_CLUSTER=${ContainerCluster}
          ECS_CONTAINER_INSTANCE_PROPAGATE_TAGS_FROM=ec2_instance
          EOF

          # Download initial wp-content data / Setup recurrent sync
          # User 'wordpress' is setup to match WordPress Apache user
          useradd -s /bin/bash -u 33 wordpress
          aws s3 sync s3://${ContentBucket}/wp-content/ /data/wp-content/
          echo "*/5 *   * * *   wordpress    /usr/local/bin/aws s3 sync --delete s3://${ContentBucket}/wp-content/ /data/wp-content/" >> /etc/crontab

          # Setup recurrent content backup job
          chmod 755 /data/scripts/backup-to-s3.sh &&
            echo "0 0   * * *   root    /data/scripts/backup-to-s3.sh ${BackupBucket}" >> /etc/crontab

  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      Cooldown: '60'
      DesiredCapacity: !Ref 'InstanceCount'
      HealthCheckGracePeriod: 30
      HealthCheckType: 'EC2'
      LaunchConfigurationName: !Ref 'LaunchConfiguration'
      MetricsCollection:
        - Granularity: 1Minute
      MaxSize: !Ref 'InstanceCount'
      MinSize: !Ref 'InstanceCount'
      VPCZoneIdentifier: !Ref 'Subnets'
      Tags:
        - Key: 'Name'
          Value: !Sub '${BaseName}-ecs-instance'
          PropagateAtLaunch: true
        - Key: 'Env'
          Value: !Ref 'Environment'
          PropagateAtLaunch: true

  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'ec2:Describe*'
                Effect: 'Allow'
                Resource: '*'
              - Action:
                  - 's3:ListBucket'
                Effect: 'Allow'
                Resource:
                  - !Sub 'arn:aws:s3:::${ContentBucket}'
                  - !Sub 'arn:aws:s3:::${BackupBucket}'
              - Action:
                  - 's3:Get*'
                  - 's3:Put*'
                Effect: 'Allow'
                Resource:
                  - !Sub 'arn:aws:s3:::${ContentBucket}/*'
                  - !Sub 'arn:aws:s3:::${BackupBucket}/*'
              - Action:
                  - 's3:DeleteObject*'
                Effect: 'Allow'
                Resource:
                  - !Sub 'arn:aws:s3:::${ContentBucket}/*'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role'

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref 'InstanceRole'

  InstanceSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable access to service'
      VpcId: !Ref 'VpcId'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 32768
          ToPort: 65535
          SourceSecurityGroupId: !Ref 'LoadBalancerSG'
      Tags:
        - Key: 'Name'
          Value: !Sub '${BaseName}-service'
        - Key: 'Env'
          Value: !Ref 'Environment'

  DatabaseIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref 'DatabaseSG'
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref 'InstanceSG'

  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: !Sub '${BaseName}-service'
      Port: 80
      Protocol: 'HTTP'
      VpcId: !Ref 'VpcId'
      HealthCheckPath: '/'
      HealthCheckProtocol: 'HTTP'
      HealthCheckPort: 'traffic-port'
      HealthCheckIntervalSeconds: 20
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-399
      Tags:
        - Key: 'Name'
          Value: !Sub '${BaseName}-service'
        - Key: 'Env'
          Value: !Ref 'Environment'

  ListenerHttpRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      ListenerArn: !Ref 'ListenerHttpArn'
      Priority: 10
      Conditions:
        - Field: 'host-header'
          Values:
            - !Ref 'WordPressDnsName'
      Actions:
        - Type: 'forward'
          TargetGroupArn: !Ref 'TargetGroup'

  ListenerHttpsRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Condition: HasHttpsListener
    Properties:
      ListenerArn: !Ref 'ListenerHttpsArn'
      Priority: 10
      Conditions:
        - Field: 'host-header'
          Values:
            - !Ref 'WordPressDnsName'
      Actions:
        - Type: 'forward'
          TargetGroupArn: !Ref 'TargetGroup'

  DomainRecord:
    Type: 'AWS::Route53::RecordSetGroup'
    Condition: 'HasHostedZone'
    Properties:
      HostedZoneName: !Ref 'WordPressHostedZone'
      RecordSets:
      - Name: !Ref 'WordPressDnsName'
        Type: 'A'
        AliasTarget:
          DNSName: !Ref 'LoadBalancerEndpoint'
          HostedZoneId: !Ref 'LoadBalancerHostedZoneId'

Outputs:

  InstanceSG:
    Description: 'Instance security group'
    Value: !Ref 'InstanceSG'
    Export:
      Name: !Sub '${AWS::StackName}-InstanceSG'
