---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Elastic FileSystem'

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'General configuration'
        Parameters:
          - 'BaseName'
          - 'Environment'
      - Label:
          default: 'Network configuration'
        Parameters:
          - 'VpcId'
          - 'Subnets'
      - Label:
          default: 'SSM configuration'
        Parameters:
          - 'SsmKeyPrefix'
    ParameterLabels:
      BaseName:
        default: 'Base resource name'
      Environment:
        default: 'Environment'
      VpcId:
        default: 'VPC Identifier'
      Subnets:
        default: 'VPC Subnets'
      SsmKeyPrefix:
        default: 'Key prefix'

Parameters:

  BaseName:
    Description: 'This name will be used to build identifiers for the components in the stack'
    Type: 'String'
    AllowedPattern: '[-_a-z0-9]+'
    ConstraintDescription: 'Invalid name. Only lowercase letters, numbers, underscores and hyphens are allowed.'
    Default: 'efs'

  Environment:
    Description: 'Stack environment name'
    Type: 'String'
    AllowedValues:
      - 'Pro'
      - 'Pre'
    Default: 'Pro'

  VpcId:
    Description: 'AWS SSM Parameter name storing the VPC identifier'
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>'
    Default: '/network/vpc-id'

  Subnets:
    Description: 'AWS SSM Parameter name storing subnets for filesystem mount targets'
    Type: 'AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>'
    Default: '/network/subnets'

  SsmKeyPrefix:
    Description: 'Key prefix for AWS Systems Manager Parameters created in this stack'
    Type: 'String'
    Default: '/filesystem'

Resources:

  ElasticFileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      PerformanceMode: 'generalPurpose'
      FileSystemTags:
        - Key: 'Name'
          Value: !Ref 'BaseName'
        - Key: 'Env'
          Value: !Ref 'Environment'

  MountTargetA:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref 'ElasticFileSystem'
      SecurityGroups:
        - !Ref 'SecurityGroup'
      SubnetId: !Select [ 0, !Ref 'Subnets' ]

  MountTargetB:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref 'ElasticFileSystem'
      SecurityGroups:
        - !Ref 'SecurityGroup'
      SubnetId: !Select [ 1, !Ref 'Subnets' ]

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable access to EFS filesystem'
      VpcId: !Ref 'VpcId'
      Tags:
        - Key: 'Name'
          Value: !Sub '${BaseName}-fs'
        - Key: 'Env'
          Value: !Ref 'Environment'

  SsmFileSystemId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${SsmKeyPrefix}/filesystem-id'
      Type: String
      Value: !Ref 'ElasticFileSystem'
      Description: !Sub '${AWS::StackName} - Filesystem Id'
      Tags:
        Name: !Sub '${BaseName}-filesystem'
        Env: !Ref 'Environment'

  SsmSecurityGroup:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${SsmKeyPrefix}/security-group'
      Type: String
      Value: !Ref 'SecurityGroup'
      Description: !Sub '${AWS::StackName} - Security group'
      Tags:
        Name: !Sub '${BaseName}-securitygroup'
        Env: !Ref 'Environment'

Outputs:

  FileSystemId:
    Description: 'FileSystem Identifier'
    Value: !Ref 'ElasticFileSystem'
    Export:
      Name: !Sub '${AWS::StackName}-FileSystemId'

  SecurityGroup:
    Description: 'Security group for the elastic filesystem'
    Value: !Ref 'SecurityGroup'
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroup'
