version: '3.8'

services:
  wordpress:
    build: ../service
    image: wordpress:local
    restart: always
    read_only: true
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://blog.wordpress.local');
        define('WP_SITEURL', 'http://blog.wordpress.local');
        define('FS_METHOD', 'direct');
        define('CONCATENATE_SCRIPTS', false);
    volumes:
      - type: volume
        source: content
        target: /var/www/html/wp-content
      - type: tmpfs
        target: /run/lock/apache2
      - type: tmpfs
        target: /run/apache2
      - type: tmpfs
        target: /tmp
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql

volumes:
  content:
  db:
